name: Gerar Video Short

on:
  workflow_dispatch:
    inputs:
      nome_roteiro:
        description: 'Nome do arquivo de roteiro'
        required: true
        default: 'roteiro.txt'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Copiar Repositório
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Instalar FFmpeg e Dependências
        run: |
          sudo apt-get update && sudo apt-get install -y ffmpeg
          pip install -r requirements.txt

      - name: Executar Gerador de Vídeos
        run: |
          python src/montador.py

      - name: Salvar Vídeo Gerado (Artifacts)
        uses: actions/upload-artifact@v4
        with:
          name: video-pronto
          path: output.mp4
